[build]
  # Build command
  command = "npm run build"
  
  # Directory to publish
  publish = "dist"
  
  # Node.js version
  [build.environment]
    NODE_VERSION = "20"
    NPM_VERSION = "10"

# Redirect rules for SPA routing
[[redirects]]
  # Handle all routes for React Router
  from = "/*"
  to = "/index.html"
  status = 200

# SEO and sitemap redirects
[[redirects]]
  # Sitemap
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200

[[redirects]]
  # Robots.txt
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    
    # Content Security Policy
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://js.hs-scripts.com https://www.google-analytics.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      font-src 'self' https://fonts.gstatic.com;
      img-src 'self' data: https: http: blob:;
      connect-src 'self' https://www.google-analytics.com https://analytics.google.com https://js.hs-scripts.com;
      frame-src 'self' https://js.hs-scripts.com;
      object-src 'none';
      base-uri 'self';
      form-action 'self';
    """
    
    # Cache control for HTML files
    Cache-Control = "public, max-age=0, must-revalidate"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache images
[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.gif"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache fonts
[[headers]]
  for = "*.woff"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.ttf"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.eot"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache CSS and JS
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache manifest and other files
[[headers]]
  for = "*.ico"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# SEO-specific headers
[[headers]]
  for = "/"
  [headers.values]
    # Canonical URL
    Link = '<https://undash-cop.com/>; rel="canonical"'
    
    # Additional SEO
    robots = "index, follow"
    googlebot = "index, follow"

# Page-specific SEO headers
[[headers]]
  for = "/about"
  [headers.values]
    Link = '<https://undash-cop.com/about>; rel="canonical"'

[[headers]]
  for = "/contact"
  [headers.values]
    Link = '<https://undash-cop.com/contact>; rel="canonical"'

[[headers]]
  for = "/products"
  [headers.values]
    Link = '<https://undash-cop.com/products>; rel="canonical"'

[[headers]]
  for = "/case-studies"
  [headers.values]
    Link = '<https://undash-cop.com/case-studies>; rel="canonical"'

[[headers]]
  for = "/blog"
  [headers.values]
    Link = '<https://undash-cop.com/blog>; rel="canonical"'

[[headers]]
  for = "/resources"
  [headers.values]
    Link = '<https://undash-cop.com/resources>; rel="canonical"'

[[headers]]
  for = "/careers"
  [headers.values]
    Link = '<https://undash-cop.com/careers>; rel="canonical"'

# Legal pages
[[headers]]
  for = "/privacy-policy"
  [headers.values]
    Link = '<https://undash-cop.com/privacy-policy>; rel="canonical"'

[[headers]]
  for = "/terms-and-conditions"
  [headers.values]
    Link = '<https://undash-cop.com/terms-and-conditions>; rel="canonical"'

[[headers]]
  for = "/refund-policy"
  [headers.values]
    Link = '<https://undash-cop.com/refund-policy>; rel="canonical"'

[[headers]]
  for = "/cookie-policy"
  [headers.values]
    Link = '<https://undash-cop.com/cookie-policy>; rel="canonical"'

[[headers]]
  for = "/support"
  [headers.values]
    Link = '<https://undash-cop.com/support>; rel="canonical"'

[[headers]]
  for = "/status"
  [headers.values]
    Link = '<https://undash-cop.com/status>; rel="canonical"'

# Dynamic routes for blog posts and case studies
[[headers]]
  for = "/blog/*"
  [headers.values]
    Link = '<https://undash-cop.com/blog/*>; rel="canonical"'

[[headers]]
  for = "/case-studies/*"
  [headers.values]
    Link = '<https://undash-cop.com/case-studies/*>; rel="canonical"'

# Error pages
[[redirects]]
  from = "/404"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/500"
  to = "/500.html"
  status = 500

# Legacy redirects (if migrating from old site)
[[redirects]]
  from = "/old-page"
  to = "/new-page"
  status = 301

# Force HTTPS
[[redirects]]
  from = "http://undash-cop.com/*"
  to = "https://undash-cop.com/:splat"
  status = 301
  force = true

# Remove trailing slashes
[[redirects]]
  from = "/*/"
  to = "/:splat"
  status = 301

# Handle www redirects
[[redirects]]
  from = "https://www.undash-cop.com/*"
  to = "https://undash-cop.com/:splat"
  status = 301
  force = true

# Plugin configurations
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Functions (if using Netlify Functions)
# [functions]
#   directory = "netlify/functions"

# Edge functions (if using Netlify Edge Functions)
# [[edge_functions]]
#   path = "/hello"
#   function = "hello"

# Environment variables (these will be set in Netlify dashboard)
# VITE_GA_TRACKING_ID
# VITE_HUBSPOT_PORTAL_ID
# VITE_HUBSPOT_CONTACT_FORM_ID
# VITE_HUBSPOT_JOB_FORM_ID
# VITE_APP_BASE_URL
# VITE_APP_ENV

# Build plugins
[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs.thresholds]
    performance = 0.9
    accessibility = 0.9
    best-practices = 0.9
    seo = 0.9

[[plugins]]
  package = "@netlify/plugin-sitemap"

  [plugins.inputs]
    buildDir = "dist"
    exclude = ["/404", "/500"]

# Branch-specific configurations
[context.production]
  command = "npm run build"
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  command = "npm run build"
  environment = { NODE_ENV = "development" }

[context.branch-deploy]
  command = "npm run build"
  environment = { NODE_ENV = "development" }
