[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"

[[redirects]]
  from = "/api/applications"
  to = "/.netlify/functions/applications"
  status = 200

[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/applications"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["formidable", "@aws-sdk/client-s3", "@aws-sdk/s3-request-presigner", "@sendgrid/mail", "zod"]

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"