name = "udc-applications-worker"
main = "workers/applications.js"
compatibility_date = "2024-01-01"

# Environment variables (set these in Cloudflare dashboard or via wrangler)
[vars]
FROM_EMAIL = "noreply@undash-cop.com"
FROM_NAME = "Undash Cop"
HR_EMAIL = "hr@undash-cop.com"

# R2 bucket binding
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "resumes"

# Secrets (set these via: wrangler secret put SECRET_NAME)
# R2_ACCOUNT_ID
# R2_ACCESS_KEY_ID  
# R2_SECRET_ACCESS_KEY
# R2_PUBLIC_URL
# SENDGRID_API_KEY (optional - if using SendGrid)
# EMAIL_WORKER_URL (optional - if using separate email worker)

# Routes (uncomment and modify as needed)
# routes = [
#   { pattern = "api.undash-cop.com/*", zone_name = "undash-cop.com" }
# ]

# Custom domain (uncomment and modify as needed)
# [env.production]
# name = "udc-applications-worker"
# routes = [
#   { pattern = "api.undash-cop.com/*", zone_name = "undash-cop.com" }
# ]
